title: Jumoke Lucas 
logo: headshot.jpg
description: Results oriented, self driven data analytics professional with over 2 years of experience using Microsoft Excel for data automation, Structured Query Language (SQL) for data manipulation & interrogation and, Power BI for business intelligence report. Passionate about transforming and analyzing data to tell a story and derive meaningful insights.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
